name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: macos-10.15
    strategy:
       fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Waiting for debugger
      uses: mxschmitt/action-tmate@v3
